I have studied untit section 4 of the masterpython and I think I will finish the 50% of the masterpython in one week and 75% of the masterpython will be finished on January 22th and I will complete it the end of January. 

In [23]:
import numpy as np
arr_t= np.array((1,2,3,4,5)) #convert list, tuple or any array-like object into the array method.
arr_2_D = np.array([[1,2,3],[4,5,6]])
arr_3_D = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a = np.array(42)
print(arr_t)
print("*" * 30)
print(arr_2_D)
print("*" * 30)
print(arr_3_D)
print("*" * 30)
print(arr_t.ndim, arr_2_D.ndim , arr_3_D.ndim, a.ndim) #ndim attribute returns an integer that tells us how many dimensions the array have.
print(arr_2_D.shape) # This array has 2 dimentions and each dimention has 3 elements.

[1 2 3 4 5]
******************************
[[1 2 3]
 [4 5 6]]
******************************
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
******************************
1 2 3 0
(2, 3)


NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficientl.

In [2]:
import pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.
Solve short hands-on challenges to perfect your data manipulation skills.

In [3]:
import matplotlib

Matplotlib.pyplot is a collection of functions that make matplotlib work like MATLAB. Each pyplot function makes some change to a figure: e.g., creates a figure, creates a plotting area in a figure, plots some lines in a plotting area, decorates the plot with labels, etc.

In [4]:
import seaborn

Seaborn is a library for making statistical graphics in Python. It builds on top of matplotlib and integrates closely with pandas data structures. Seaborn helps you explore and understand your data.

In [24]:
import scipy

SciPy is a collection of mathematical algorithms and convenience functions built on the NumPy extension of Python. It adds significant power to the interactive Python session by providing the user with high-level commands and classes for manipulating and visualizing data. With SciPy, an interactive Python session becomes a data-processing and system-prototyping environment rivaling systems, such as MATLAB, IDL, Octave, R-Lab, and SciLab.